WIP on getting spark to save metadata in hive server
Current error when running

```
spark = get_spark_session()
namespace = "fastgenomics"
spark.sql(f"CREATE DATABASE IF NOT EXISTS {namespace}")
```

is

```
AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException:
MetaException(message:Unable to create database path
file:/cdm_shared_workspace/spark_arg_warehouse/fastgenomics.db, failed
to create database fastgenomics)
```

The changes in the code can probably be pared down a lot when it's clear
what's actually needed and what works, lots of experimentation & cruft
in there currently